import initScrollSuave from "./modules/scrollSuave.js";
import initScrollAnimacao from "./modules/scrollAnimacao.js";
import initAccordion from "./modules/accordion.js";
import initTab from "./modules/tab.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropDownMenu from "./modules/dropDownMenu.js";
import initMenuMobile from "./modules/menuMobile.js";
import initHorarioFuncionamento from "./modules/horarioFuncionamento.js";
import initFetchAnimais from "./modules/fetchAnimais.js";
import initFetchBitcoin from "./modules/fetchBitcoin.js";

initScrollSuave();
initScrollAnimacao();
initAccordion();
initTab();
initModal();
initTooltip();
initDropDownMenu();
initMenuMobile();
initHorarioFuncionamento();
initFetchAnimais();
initFetchBitcoin();
